"use client";

import { useEffect } from "react";

/**
 * Registers the Service Worker generated by @serwist/next.
 *
 * - Only runs in production builds (dev builds do not generate /sw.js).
 * - Uses an explicit `scope: "/"` so the SW controls all routes.
 * - No-ops when `navigator.serviceWorker` is unavailable (e.g. SSR, older Safari without HTTPS).
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (process.env.NODE_ENV !== "production") {
      return;
    }
    if (typeof window === "undefined") {
      return;
    }
    if (!("serviceWorker" in navigator)) {
      return;
    }

    navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch((err) => {
      console.warn("Service worker registration failed:", err);
    });
  }, []);

  return null;
}
